# flow-file.yaml
# Author: Adeel Malik

stages:
  validateChangelog:
    actions:
      - type: liquibase
        command: validate

      - type: liquibase
        command: status

  DriftDetection:
    actions:
      - type: liquibase
        command: diff
        cmdArgs: { 
          format: "JSON",
          reference-url: "offline:sqlserver?snapshot=snapshot.json"
        }
        globalArgs: { 
          output-file: "diff.json",
          report-name: "diff.html"
        }

  PolicyChecks:
    actions:
      - type: liquibase
        command: checks run
        cmdArgs: { 
          checks-settings-file: "policychecks/liquibase.checks-settings.conf"
        }
        globalArgs: { 
          report-name: "checks.html"
        }

  liquibaseUpdate:
    actions:
      - type: liquibase
        command: update-sql
        cmdArgs: { }

      - type: liquibase
        # if: "${IS_ROLLBACK} == false"
        command: tag
        cmdArgs: { tag: "adeelM-demo"}
      - type: liquibase
        # if: "${IS_ROLLBACK} == false"
        command: update

    # - type: liquibase
    #   if: "${IS_ROLLBACK} == true"
    #   command: rollbackOneUpdate
    #   cmdArgs: { force: "true" }

  Snapshot:
    actions:
      - type: liquibase
        command: snapshot
        cmdArgs: { 
          snapshot-format: "JSON"
        }
        globalArgs: { 
          output-file: "snapshot.json"
        }

endStage:
  actions:
    - type: liquibase
      command: history
      cmdArgs: {}